### PR TITLE
feat: add terraform integration

### PR DESCRIPTION
**Pull request by jannis-a**
- **feat(terraform): initial integration with github and tf cloud**
- **feat(ci): add terraform plan**

### CODE REVIEW

**Comment by bobo-le** [comment]
Na

**Comment by jannis-a** [comment]
test

**Comment by jannis-a** [comment]
asdasdasd

**Comment by jannis-a** [comment]
test

**Comment by jannis-a** [comment]
foobar

**Comment by jannis-a** [comment]
test

**Comment by jannis-a** [comment]
asdasd

**Comment by jannis-a** [comment]
test

**Pull request merged**
